name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Updated to a more recent Node.js version
      - name: Install dependencies
        run: |
          npm ci
          npm install @headlessui/react  # Explicitly install @headlessui/react
      - name: List installed packages
        run: npm list # This will help diagnose any package issues
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
