name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main # Trigger deployment on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use the version of Node.js that your project requires

      - name: Install dependencies
        run: npm install # Install npm dependencies

      - name: Build project
        run: npm run build # Build the project with npm

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages # Deploy to the gh-pages branch
          publish_dir: ./dist
